training:
  max_epochs: 20
  lr: 0.001
  logger: false
  max_iterations: 20
  mode: open-loop
dataset:
  input_labels:
  - dx
  - dy
  - dz
  - vx
  - vy
  - vz
  - phi
  - theta
  - psi
  - p
  - q
  - r
  - Mx_ext
  - My_ext
  - Mz_ext
  - omega
  output_labels:
  - u
  train_path: datasets/hover_dataset_train.npz
  val_path: datasets/hover_dataset_val.npz
  normalized: true
  with_noise: false
  with_bias: false
  input_size: 19
  output_size: 4
closed_loop:
  starting_seq: 15
  seq_len: 15
  lambda_cmd: 0.8
  lambda_pos: 0.1
  freq_timesteps: 5
mlp_block:
  no_layers:
  - 120
  - 120
  - 120
  value: false
conv_block:
  value: true
sequencing:
  value: true
  seq_len: 1
dataloader:
  batch_size: 32
  num_workers: 8
  pin_memory: false
  drop_last: true
model:
  no_neurons_layer: 64
